title: Katie Brady
author: Katie Brady
author_title: Web Developer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/realsimple"
twitter_url: https://twitter.com/YOURTWITTERNAME
linkedin_url: https://www.linkedin.com/in/YOURLINKEDINADDRESS
github_url: https://github.com/YOURGITHUBNAME

# Build settings
markdown: kramdown
theme: realsimple
exclude:
  - Gemfile
  - Gemfile.lock
